# Coding Temple's Data Analytics Program
---
## Intro to Pandas Assignment
---

### Imports

In [30]:
import pandas as pd

### Exercise #1: Read in the Data
For this assignment, you will want to use the Boston RedSox data from earlier today. Practice reading this into a DataFrame object using Pandas

In [31]:
bs_2017 = pd.read_csv(r'C:\Users\nargi\Documents\coding temple\data\redsox 2017 hitting.txt')
bs_2017

,Rk,Pos,Name,Age,G,PA,AB,R,H,2B,...,OBP,SLG,OPS,OPS+,TB,GDP,HBP,SH,SF,IBB
0,1,C,Christian Vazquez,26,99,345,324,43,94,18,...,0.330,0.404,0.735,91,131,14,3,0,1,0
1,2,1B,Mitch Moreland,31,149,576,508,73,125,34,...,0.326,0.443,0.769,99,225,14,6,0,5,6
2,3,2B,Dustin Pedroia,33,105,463,406,46,119,19,...,0.369,0.392,0.760,100,159,11,2,2,4,4
3,4,SS,Xander Bogaerts,24,148,635,571,94,156,32,...,0.343,0.403,0.746,95,230,17,6,0,2,6
4,5,3B,Rafael Devers,20,58,240,222,34,63,14,...,0.338,0.482,0.819,111,107,5,0,0,0,3
5,6,LF,Andrew Benintendi,22,151,658,573,84,155,26,...,0.352,0.424,0.776,102,243,16,6,1,8,7
6,7,CF,Jackie Bradley Jr.,27,133,541,482,58,118,19,...,0.323,0.402,0.726,89,194,8,9,0,2,4
7,8,RF,Mookie Betts,24,153,712,628,101,166,46,...,0.344,0.459,0.803,108,288,9,2,0,5,9
8,9,DH,Hanley Ramirez,33,133,553,496,58,120,24,...,0.320,0.429,0.750,94,213,15,6,0,0,8
9,10,C,Sandy Leon,28,85,301,271,32,61,14,...,0.290,0.354,0.644,68,96,5,1,1,3,1
10,11,UT,Chris Young,33,90,276,243,30,57,12,...,0.322,0.387,0.709,85,94,4,2,0,1,0
11,12,3B,Deven Marrero,26,71,188,171,32,36,9,...,0.259,0.333,0.593,54,57,8,0,3,2,0
12,13,2B,Eduardo Nunez,30,38,173,165,23,53,12,...,0.353,0.539,0.892,128,89,3,2,0,0,0
13,14,2B,Brock Holt,29,64,164,140,20,28,6,...,0.305,0.243,0.548,47,34,3,3,0,2,0
14,15,IF,Josh Rutledge,28,37,118,107,10,24,2,...,0.297,0.262,0.558,49,28,1,2,0,0,0
15,16,3B,Pablo Sandoval,30,32,108,99,10,21,2,...,0.269,0.354,0.622,61,35,4,0,0,1,0
16,17,UT,Sam Travis,23,33,83,76,13,20,6,...,0.325,0.342,0.667,75,26,2,1,0,0,0
17,18,UT,Tzu-Wei Lin,23,25,66,56,7,15,0,...,0.369,0.339,0.709,88,19,0,0,1,0,0
18,19,IF,Marco Hernandez,24,21,60,58,7,16,3,...,0.300,0.328,0.628,65,19,0,1,0,0,0
19,20,UT,Rajai Davis,36,17,38,36,7,9,2,...,0.289,0.306,0.595,56,11,2,1,0,0,0
20,21,UT,Steve Selsky,27,8,9,9,0,1,1,...,0.111,0.222,0.333,-16,2,0,0,0,0,0
21,22,UT,Blake Swihart,25,6,7,5,1,1,0,...,0.429,0.200,0.629,74,1,0,0,0,0,0
22,23,2B,Chase d'Arnaud,30,2,1,1,2,1,0,...,1.000,1.000,2.000,428,1,0,0,0,0,0

### Exercise #2 - Find the Total Number of Runs and RBIs for the Red Sox <br>
<p>Get total number of home runs and rbi's</p>

In [33]:
bs_2017['HR'].sum()

168

In [34]:
bs_2017['RBI'].sum()

735

### Exercise #3: Grouping
Find the 5 players with the highest `OPS+`

In [43]:
bs_2017.sort_values(by = 'OPS+', ascending = False)[['Name','OPS+']].head(5)

                 Name  OPS+
22     Chase d'Arnaud   428
12      Eduardo Nunez   128
4       Rafael Devers   111
7        Mookie Betts   108
5   Andrew Benintendi   102

### Exercise #4: To SQL
In this exercise, you will send your dataframe objects to an elephantSQL instance. Once you have successfully uploaded your dataframes, load them into a new dataframe using the `read_sql_table()` function.